#!/usr/bin/env bash

VERSION='0.1.0'

set -euo pipefail

function usage() {
  cat <<EOF

Usage:

# kubectl gopass apply [optional kubectl apply params] my-secret
    applies secret "my-secret" via kubectl. Namespace and other params can be
    specified and are passed through to kubectl.

# kubectl gopass apply-recursive [optional kubectl apply params] my-secret-path
    like apply but takes a path and applies all secrets below that path

# kubectl gopass diff [optional kubectl apply params] my-secret
    shows the secret diff of "my-secret" via kubectl. Namespace and other 
    params can be specified and are passed through to kubectl.

# kubectl gopass diff-recursive [optional kubectl apply params] my-secret-path
    like diff but takes a path and applies all secrets below that path
    
# kubectl gopass create my-new-secret
    create a new secret prefilled with a kubernetes secret template and starts
    an editor to edit the newly created secret

# kubectl gopass fetch [optional kubectl get secret params] secret-name dir/to/gopass-secret
    fetches a secret with name from the kubernetes cluster and stores in in gopass as dir/to/gopass-secret

# kubectl gopass fetchrecursive [optional kubectl get secret params] dir/to/gopass-secret-path
    fetches all secrets from the kubernetes cluster (namespace) and stores them in gopass dir/to/gopass-secret-path

# kubectl gopass version
    prints out the kubectl-gopass version ($VERSION)

# kubectl gopass help
    prints these usage instructions

Gopass and kubectl is required for all functionality, jq and yq are required for fetching secrets from kubernetes to gopass.

EOF
}

diff_or_apply(){
  if [[ "$#" -lt 2 ]]; then
    echo >&2 "Too few arguments, secret is required"
    usage
    exit 1
  fi
  SECRET="${*: -1}"

  KUBECTL_ARGS=("$@")
  unset "KUBECTL_ARGS[${#KUBECTL_ARGS[@]}-1]"
  unset "KUBECTL_ARGS[0]"
  LEN_KUBECTL_ARGS=${#KUBECTL_ARGS[@]}
  if [[ "$LEN_KUBECTL_ARGS" -lt 1 ]]; then
    echo "will $1 secret $SECRET"
  else
    echo "will $1 secret $SECRET with additional kubectl args '" "${KUBECTL_ARGS[@]}" "'"
  fi
  $GOPASS show "$SECRET" | $KUBECTL "$1" ${KUBECTL_ARGS[@]+"${KUBECTL_ARGS[@]}"} -f -
}

recursive() {
  if [[ "$#" -lt 2 ]]; then
    echo >&2 "Too few arguments, secret path is required"
    usage
    exit 1
  fi

  SECRETPATH="${*: -1}"

  KUBECTL_ARGS=("$@")
  unset "KUBECTL_ARGS[${#KUBECTL_ARGS[@]}-1]"
  unset "KUBECTL_ARGS[0]"

  IFS=$'\n'
  for SECRET in $(gopass ls -f "$SECRETPATH"); do
    diff_or_apply "$1" ${KUBECTL_ARGS[@]+"${KUBECTL_ARGS[@]}"} "$SECRET" || true
  done
}

create() {
  if [[ "$#" -lt 1 ]]; then
    echo >&2 "Too few arguments, target secret is required"
    usage
    exit 1
  fi
  SECRETNAME=${*:(-1)}

  gopass insert "$SECRETNAME" <<EOL
apiVersion: v1
kind: Secret
metadata:
  name: ${SECRETNAME//\//-}
type: Opaque
stringData:
  key: value
  otherkey: othervalue
EOL
  gopass edit "$SECRETNAME"
  exit 0
}

fetch() {
  if [[ "$#" -lt 3 ]]; then
    echo >&2 "Too few arguments, kubernetes secret and target gopass secret is required"
    usage
    exit 1
  fi
  SECRET="${*: (-2):1}"
  TARGET="${*: -1}"

  KUBECTL_ARGS=("$@")
  unset "KUBECTL_ARGS[${#KUBECTL_ARGS[@]}-1]"
  unset "KUBECTL_ARGS[0]"
  LEN_KUBECTL_ARGS=${#KUBECTL_ARGS[@]}
  if [[ "$LEN_KUBECTL_ARGS" -lt 1 ]]; then
    echo "will fetch secret $SECRET"
  else
    echo "will fetch secret $SECRET with additional kubectl args '" "${KUBECTL_ARGS[@]}" "'"
  fi
  $KUBECTL get secret ${KUBECTL_ARGS[@]+"${KUBECTL_ARGS[@]}"} $SECRET -o json | \
  $JQ 'del(.metadata.creationTimestamp)|del(.metadata.resourceVersion)|del(.metadata.selfLink)|del(.metadata.uid)|.data[] |= @base64d | . + {"stringData": .data} | del(.data)' | \
  $YQ read - | \
  $GOPASS insert "${TARGET}"
}

fetchrecursive() {
  if [[ "$#" -lt 2 ]]; then
    echo >&2 "Too few arguments, target gopass path is required"
    usage
    exit 1
  fi
  TARGET="${*: -1}"

  KUBECTL_ARGS=("$@")
  unset "KUBECTL_ARGS[${#KUBECTL_ARGS[@]}-1]"
  unset "KUBECTL_ARGS[0]"
  LEN_KUBECTL_ARGS=${#KUBECTL_ARGS[@]}
  if [[ "$LEN_KUBECTL_ARGS" -lt 1 ]]; then
    echo "will fetch secrets to  $TARGET"
  else
    echo "will fetch secrets to  $TARGET with additional kubectl args '" "${KUBECTL_ARGS[@]}" "'"
  fi

  for SECRET in $($KUBECTL get secrets -o json | $JQ -r ".items[].metadata.name"); do
    echo "fetching ${SECRET}"
    $KUBECTL get secret ${KUBECTL_ARGS[@]+"${KUBECTL_ARGS[@]}"} $SECRET -o json | \
    $JQ 'del(.metadata.creationTimestamp)|del(.metadata.resourceVersion)|del(.metadata.selfLink)|del(.metadata.uid)|.data[] |= @base64d | . + {"stringData": .data} | del(.data)' | \
    $YQ read - | \
    $GOPASS insert "${TARGET}/${SECRET}"
  done
}

main() {
  if hash kubectl 2>/dev/null; then
    KUBECTL=kubectl
  elif hash kubectl.exe 2>/dev/null; then
    KUBECTL=kubectl.exe
  else
    echo >&2 "kubectl is not installed"
    exit 1
  fi

  if hash gopass 2>/dev/null; then
    GOPASS=gopass
  elif hash gopass.exe 2>/dev/null; then
    GOPASS=gopass.exe
  else
    echo >&2 "gopass is not installed"
    exit 1
  fi

  if hash jq 2>/dev/null; then
    JQ=jq
  else
    echo >&2 "jq is not installed, fetching secrets from kubernetes to gopass will not work"
  fi

  if hash yq 2>/dev/null; then
    YQ=yq
  else
    echo >&2 "yq is not installed, fetching secrets from kubernetes to gopass will not work"
  fi

  if [[ "$#" -eq 0 ]]; then
    usage | less
    return
  fi

  case "$1" in
  '-h' | '--help' | 'help')
    usage | less
    ;;
  'apply'|'diff')
    diff_or_apply "${@:1}"
    exit 0
    ;;
  'diff-recursive'| 'recursive-diff')
    recursive "diff" "${@:2}"
    ;;
  'apply-recursive'| 'recursive-apply')
    recursive "apply" "${@:2}"
    ;;
  'create')
    create "${@:1}"
    ;;
  'fetch')
    fetch "${@:1}"
    ;;
  'fetch-recursive')
    fetchrecursive "${@:1}"
    ;;
  'version')
    echo "$VERSION"
    exit 0
    ;;
   -*)
    usage
    error "unrecognized flag \"${1}\""
    ;;
   *)
    usage
    error "unknown command \"$1\""
  esac

}

main "$@"
